#!/usr/bin/env node
// Pulls the game's shared logic out of its client bundle into tools/parity/game-shared.js.
//
//   node tools/parity/extract.js [src/game_index-12d386a8.js] [src/game_vendor-a3a301f0.js]
//
// moomoo.io's client bundle carries the server's own shared modules: the player, the
// animals, game objects, the object manager, projectiles, the config, the data tables
// and the helpers they use (with the server's send calls still in them). The private
// server is checked against these by tools/server-parity.js. The bundle is formatted
// with prettier (needs it installed), then each piece is cut out by its name; nothing
// in the bundle is run here.

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const ROOT = path.resolve(__dirname, "..", "..");
const INDEX = path.resolve(process.argv[2] || path.join(ROOT, "src/game_index-12d386a8.js"));
const VENDOR = path.resolve(process.argv[3] || path.join(ROOT, "src/game_vendor-a3a301f0.js"));
const OUT = path.join(__dirname, "game-shared.js");

const tmp = path.join(require("os").tmpdir(), "parity-" + process.pid + ".js");
fs.copyFileSync(INDEX, tmp);
execSync("prettier --write --print-width 120 " + JSON.stringify(tmp), { stdio: "ignore" });
const lines = fs.readFileSync(tmp, "utf8").split("\n");
fs.unlinkSync(tmp);

// a piece starts at the line that matches and ends at the first line, at the same
// indentation, that closes it
const cut = (startRe, name) => {
  const i = lines.findIndex(l => startRe.test(l));
  if (i < 0) throw new Error("not found: " + name);
  // "const a = [" in a chain of consts closes one level in ("  ],")
  const indent = lines[i].match(/^\s*/)[0] + (/^const [\w$]+ = \[$/.test(lines[i]) ? "  " : "");
  const close = new RegExp("^" + indent + "(\\}|\\]|\\))[,;)]*$");
  for (let j = i + 1; j < lines.length; j++) if (close.test(lines[j])) return { name, from: i + 1, to: j + 1, text: lines.slice(i, j + 1).join("\n") };
  throw new Error("no end: " + name);
};
const piece = (re, name, rename) => {
  const p = cut(re, name);
  let text = p.text.replace(/^\s+/, "").replace(/,\s*$/, "");
  if (rename) text = rename(text);
  return { ...p, text };
};
const fn = (name, as) => piece(new RegExp("^function " + name + "\\("), as, t => t.replace("function " + name + "(", "function " + as + "("));
const helper = (name, as) => piece(new RegExp("^\\s+" + name.replace(/\$/g, "\\$") + " = function \\("), as, t => "const " + as + t.slice(name.length));
const table = (re, name, as) => piece(re, name, t => "const " + as + " = " + t.replace(/^(const )?[\w$]+ = /, ""));

const parts = [
  // the config (its numbers in a row of consts, then the object)
  (() => {
    const a = lines.findIndex(l => /^const qf = 1920,$/.test(l));
    const b = lines.findIndex((l, i) => i > a && /^  W = \{$/.test(l));
    const p = cut(/^  W = \{$/, "config");
    return { name: "config", from: a + 1, to: p.to, text: lines.slice(a, p.to).join("\n").replace(/^  W = \{/m, "  config = {").replace(/\};$/, "};") };
  })(),
  helper("ah", "randInt"), helper("rh", "randFloat"), helper("lh", "lerp"), helper("ch", "decel"), helper("dh", "getDistance"),
  helper("fh", "getDirection"), helper("uh", "getAngleDist"), helper("hh", "isNumber"), helper("gh", "fixTo"), helper("yh", "sortByPoints"),
  helper("kh", "lineInRect"),
  table(/^const ue = \[$/, "groups", "ue"),
  table(/^  Xh = \[$/, "projectiles", "projectileTable"),
  table(/^  zh = \[$/, "weapons", "weapons"),
  table(/^  go = \[$/, "items", "itemList"),
  table(/^const jh = \[$/, "hats", "hats"),
  table(/^  \$h = \[$/, "accessories", "accessories"),
  table(/^  Qh = \[$/, "name words", "gameWords"),
  fn("Hh", "ObjectManager"), fn("Vh", "ProjectileManager"), fn("Kh", "AiManager"), fn("Jh", "AI"), fn("Uh", "GameObject"),
  fn("Zh", "Player"), fn("em", "Projectile")
];

// the bad-words package's lists, from the vendor bundle
const vendor = fs.readFileSync(VENDOR, "utf8");
const list = (re, what) => {
  const m = vendor.match(re);
  if (!m) throw new Error("not in the vendor bundle: " + what);
  return m[1];
};
const badWords = "const badWordsWords = " + list(/,Ce=(\[[^\]]*\]),Le=\{words:Ce\}/, "words") + ";\nconst badWordsArray = " + list(/,Be=(\[[^\]]*\]),Re=/, "array") + ";";

const header = `// GENERATED by tools/parity/extract.js from ${path.basename(INDEX)} and ${path.basename(VENDOR)}.
// The game's own shared logic, cut out unchanged (formatted). Not part of Ryn; used only by
// tools/server-parity.js to check the private server against the game. Each piece names
// the lines it came from in the formatted bundle.
`;
const body = parts.map(p => "// " + p.name + " (lines " + p.from + "-" + p.to + ")\n" + p.text + ";").join("\n\n");
const tail = `
const ih = Math.sqrt, l0 = Math.abs, sh = Math.atan2, wa = Math.PI;
const ro = Math.PI * 2, Ca = 0;
const sc = Math.floor, ac = Math.abs, ti = Math.cos, ni = Math.sin, qh = Math.sqrt;
const rc = Math.abs, lo = Math.cos, co = Math.sin, lc = Math.pow, Yh = Math.sqrt;
${badWords}
// the game's names for what the pieces above use
const W = config, s = config, n = config;
const h = { randInt, randFloat, lerp, decel, getDistance, getDirection, getAngleDist, isNumber, fixTo, sortByPoints, lineInRect };
for (let e = 0; e < itemList.length; ++e) ((itemList[e].id = e), itemList[e].pre && (itemList[e].pre = e - itemList[e].pre));
const items = { groups: ue, projectiles: projectileTable, weapons, list: itemList };
const W0 = { list: badWordsWords.concat(badWordsArray, gameWords) };
module.exports = { config, utils: h, items, hats, accessories, nameFilter: W0.list, ObjectManager, ProjectileManager, AiManager, AI, GameObject, Player, Projectile };
`;
fs.writeFileSync(OUT, header + "const er = null;\n" + body.replace(/const config = \{/, "config = {") + "\n" + tail);
console.log("wrote " + path.relative(ROOT, OUT) + ": " + parts.map(p => p.name).join(", "));
